global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "rules/*.yml"

scrape_configs:

  - job_name: "order-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["order-service:8081"]

  - job_name: "payment-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["payment-service:8082"]

  - job_name: "inventory-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["inventory-service:8083"]

  - job_name: "notification-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["notification-service:8084"]

  - job_name: "api-gateway"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["api-gateway:8080"]

  - job_name: "kafka"
    static_configs:
      - targets:
        - "kafka-exporter:9308"
