resilience4j:
  retry:
    instances:
      payment-kafka:
        max-attempts: 3
        wait-duration: 500ms

  circuitbreaker:
    instances:
      payment-kafka:
        failure-rate-threshold: 50
        sliding-window-size: 10
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 10s

  bulkhead:
    instances:
      payment-kafka:
        max-concurrent-calls: 5

  thread-pool-bulkhead:
    instances:
      payment-kafka:
        core-thread-pool-size: 4
        max-thread-pool-size: 8
        queue-capacity: 20
