resilience4j:
  circuitbreaker:
    instances:
      payment-kafka:
        slidingWindowSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
      payment-producer:
        max-attempts: 3
        wait-duration: 500ms

  retry:
    instances:
      payment-kafka:
        maxAttempts: 3
        waitDuration: 500ms
      payment-producer:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s